<<<<<<< HEAD
<<<<<<< HEAD
spring.application.name=StaffDetails
server.port=9206


# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/springStaff414?createDatabaseIfNotExist=true
=======
spring.application.name=Employee
server.port=8475
=======
spring.application.name=Employee Project Spring
server.port=8346
>>>>>>> cdcaea5 (initial-commit)



# Database Connection
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/spring_EmployeeMVC_18_12_25?createDatabaseIfNotExist=true
>>>>>>> 6af7f9638ea240a8cbc631d89642ec9a6277e06f
=======
spring.datasource.url=jdbc:mysql://localhost:3306/spring_DemoEmployee_414?createDatabaseIfNotExist=true
>>>>>>> cdcaea5 (initial-commit)
spring.datasource.username=root
spring.datasource.password=abhijeet@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
<<<<<<< HEAD
<<<<<<< HEAD
=======



spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
>>>>>>> 6af7f9638ea240a8cbc631d89642ec9a6277e06f
=======

>>>>>>> cdcaea5 (initial-commit)
